In [61]:
import numpy as np

# Case 1
# moving patch without stride on 1d arrays (stride =0) 
n          = 15
patch_size = 4 
a          = np.arange(n).reshape(1,n)

print(a)
print('\n')

patch      = np.zeros((1,patch_size))
b          = a.copy()
for i in range(n-patch_size+1):
    #print(b)
    b[:,i:i+patch.size] = patch
    #print(range(i,i+patch.size))
    #print(b)
    #print('\n')
    b      = a.copy()
#explicit formula for the number of moving patches we have:
#print(n-patch.size+1)
#print(len(range(n - patch_size + 1)))
#print("success!")

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]


a: [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
range(0, 4)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[ 0  0  0  0  4  5  6  7  8  9 10 11 12 13 14]]
range(3, 7)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[ 0  1  2  0  0  0  0  7  8  9 10 11 12 13 14]]
range(6, 10)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[ 0  1  2  3  4  5  0  0  0  0 10 11 12 13 14]]
range(9, 13)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[ 0  1  2  3  4  5  6  7  8  0  0  0  0 13 14]]
4
4.0


In [66]:
# Case 2
#moving patch with a stride on 1d arrays
#How to consider the stride and patch_size simultaneously?
n          = 15
patch_size = 6 
stride     = 3

a          = np.arange(n).reshape(1,n)
print("a:", a)

patch      = np.zeros((1,patch_size))

c          = a.copy()
for i in range(0, n-patch.size+1, stride):
    print(range(i, i+patch.size))
    print(c)
    c[:, i : i + patch.size] = patch
    print(c)
    c      = a.copy()

print(len(range(0, n - patch.size + 1, stride)))
# in this case finding an explicit formula would
#be difficult since we need to consider at least
#8 different scenarios.
#So let's just use the "len" method on the range object
#print((n - patch_size + 1)/stride) Doesn't always work!

a: [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
range(0, 6)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[ 0  0  0  0  0  0  6  7  8  9 10 11 12 13 14]]
range(3, 9)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[ 0  1  2  0  0  0  0  0  0  9 10 11 12 13 14]]
range(6, 12)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[ 0  1  2  3  4  5  0  0  0  0  0  0 12 13 14]]
range(9, 15)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[0 1 2 3 4 5 6 7 8 0 0 0 0 0 0]]
4
<class 'range'>


In [73]:
# Case 3
#moving patch with a stride on 2d arrays
#How to consider the stride and patch_size simultaneously?
n1          = 11
n2          = 9
#_______________
stride1     = 4
stride2     = 2
#_______________
patchsize1  = 4
patchsize2  = 5
#_______________
a          = np.arange(n1*n2).reshape(n1,n2)
print(a)
#_______________

patch      = np.zeros((patchsize1,patchsize2))
c          = a.copy()
count      = 0
for i in range(0, n1-patchsize1+1, stride1):
    for j in range(0, n2-patchsize2+1, stride2):
        print(range(i, i + patchsize1))
        print(range(j, j + patchsize2))
        #print(c)
        c[i : i + patchsize1, j : j + patchsize2] = patch
        print(c)
        c      = a.copy()
        count +=1

m1 = len(range(0, n1 - patchsize1 + 1, stride1))
m2 = len(range(0, n2 - patchsize2 + 1, stride2))
print(m1)
print(m2)
print(m1*m2)
print(count)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98]]
range(0, 4)
range(0, 5)
[[ 0  0  0  0  0  5  6  7  8]
 [ 0  0  0  0  0 14 15 16 17]
 [ 0  0  0  0  0 23 24 25 26]
 [ 0  0  0  0  0 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98]]
range(0, 4)
range(2, 7)
[[ 0  1  0  0  0  0  0  7  8]
 [ 9 10  0  0  0  0  0 16 17]
 [18 19  0  0  0  0  0 25 26]
 [27 28  0  0  0  0  0 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 

In [100]:
# Finally
# Case 3
#moving patch with a stride on 2d arrays
#How to consider the stride and patch_size simultaneously?
n1          = 11
n2          = 9
#_______________
stride1     = 4
stride2     = 2
#_______________
patchsize1  = 4
patchsize2  = 5
#_______________
a          = np.arange(n1*n2).reshape(n1,n2)
a          = np.lib.pad(a, [(3,3),(3,3)], 'constant', constant_values =(0,0))
print(a)

nonz_a = a.nonzero() 
#print(nonz_a)

min_r = np.min(nonz_a, axis = 1)[0]
min_c = np.min(nonz_a, axis = 1)[1]
max_r = np.max(nonz_a, axis = 1)[0]
max_c = np.max(nonz_a, axis = 1)[1]

print(min_r)
print(min_c)
print(max_r)
print(max_c)

#_______________
patch      = np.zeros((patchsize1,patchsize2))
count      = 0
for i in range(min_r, max_r-patchsize1 + stride1, stride1):
    for j in range(min_c, max_c-patchsize2 +stride2, stride2):
        print(range(i, i + patchsize1))
        print(range(j, j + patchsize2))
        c          = a.copy()
        #print(c)
        c[i : i + patchsize1, j : j + patchsize2] = patch
        print(c)
        count +=1

m1 = len(range(min_r, max_r-patchsize1 + stride1, stride1))
m2 = len(range(min_c, max_c-patchsize2 +stride2, stride2))
print(m1)
print(m2)
print(m1*m2)
print(count)


[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  2  3  4  5  6  7  8  0  0  0]
 [ 0  0  0  9 10 11 12 13 14 15 16 17  0  0  0]
 [ 0  0  0 18 19 20 21 22 23 24 25 26  0  0  0]
 [ 0  0  0 27 28 29 30 31 32 33 34 35  0  0  0]
 [ 0  0  0 36 37 38 39 40 41 42 43 44  0  0  0]
 [ 0  0  0 45 46 47 48 49 50 51 52 53  0  0  0]
 [ 0  0  0 54 55 56 57 58 59 60 61 62  0  0  0]
 [ 0  0  0 63 64 65 66 67 68 69 70 71  0  0  0]
 [ 0  0  0 72 73 74 75 76 77 78 79 80  0  0  0]
 [ 0  0  0 81 82 83 84 85 86 87 88 89  0  0  0]
 [ 0  0  0 90 91 92 93 94 95 96 97 98  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
3
3
13
11
range(3, 7)
range(3, 8)
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 