In [29]:
#from sklearn.feature_extraction import image
#neighbors = image.extract_patches_2d(img, (3, 3))
import numpy as np
a = np.arange(80).reshape((8,10))
print(a)
a_padded = np.lib.pad(a, [(2,2),(2,2)], 'constant', constant_values=(0, 0))
print(a_padded)
w = 2
h = 2

print(a_padded.nonzero())
print(np.min(a_padded.nonzero(), axis = 1))
print(np.max(a_padded.nonzero(), axis = 1))
print(a_padded[2,2])
print(a_padded[2,6])
print(a_padded[6,2])
print(a_padded[6,6])

max_r = np.max(a_padded.nonzero(), axis = 1)[0]
max_c = np.max(a_padded.nonzero(), axis = 1)[1]
min_r = np.min(a_padded.nonzero(), axis = 1)[0]
min_c = np.min(a_padded.nonzero(), axis = 1)[1]

strides1 = 2
strides2 = 2
for i in range(min_r,max_r-w+2, strides1):
    for j in range(min_c, max_c-h+2, strides2):
        a_tmp = a_padded.copy()
        a_tmp[i:i+w, j:j+h] = 0
        print("index: ", i, j)
        print(a_tmp)
        print(2*'\n')
        

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]]
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  2  3  4  5  6  7  8  9  0  0]
 [ 0  0 10 11 12 13 14 15 16 17 18 19  0  0]
 [ 0  0 20 21 22 23 24 25 26 27 28 29  0  0]
 [ 0  0 30 31 32 33 34 35 36 37 38 39  0  0]
 [ 0  0 40 41 42 43 44 45 46 47 48 49  0  0]
 [ 0  0 50 51 52 53 54 55 56 57 58 59  0  0]
 [ 0  0 60 61 62 63 64 65 66 67 68 69  0  0]
 [ 0  0 70 71 72 73 74 75 76 77 78 79  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
(array([2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7